export const data = [
    {
        name: 'Diani',
        location: 'Tropical Paradise',
        rating: 4.3,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/DianiWanderlust.jpg',
        category: 'beach',
      },
      {
        name: 'Watamu',
        location: 'Sunny Island',
        rating: 4.5,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card2.jpg',
        category: 'beach',
      },
      {
        name: 'Mombasa',
        location: 'Exotic Coast',
        rating: 4.7,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card3.jpg',
        category: 'beach',
      },
      {
        name: 'Samburu',
        location: 'Jungle Adventure',
        rating: 4.6,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/SamburuWanderlust.jpg',
        category: 'safaris',
      },
      {
        name: 'Tsavo',
        location: 'Wild Savannah',
        rating: 4.2,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/TsavoWanderlust.jpg',
        category: 'safaris',
      },
      {
        name: 'Amboseli',
        location: 'Serengeti Plains',
        rating: 4.8,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/AmboseliWanderlust.jpg',
        category: 'safaris',
      },
      {
        name: 'Breathtaking Mountain 1',
        location: 'Snowy Peaks',
        rating: 4.4,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card5.jpg',
        category: 'mountains',
      },
      {
        name: 'Scenic Mountain 2',
        location: 'Misty Highlands',
        rating: 4.9,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card5.jpg',
        category: 'mountains',
      },
      {
        name: 'Grand Mountain 3',
        location: 'Alpine Vista',
        rating: 4.5,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card5.jpg',
        category: 'mountains',
      },
      {
        name: 'Refreshing Waterfall 1',
        location: 'Crystal Cascades',
        rating: 4.1,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card5.jpg',
        category: 'waterfall',
      },
      {
        name: 'Soothing Waterfall 2',
        location: 'Hidden Oasis',
        rating: 4.6,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card5.jpg',
        category: 'waterfall',
      },
      {
        name: 'Enchanting Waterfall 3',
        location: 'Rainforest Retreat',
        rating: 4.7,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card5.jpg',
        category: 'waterfall',
      },
  
  ];