export const data = [
    {
        name: 'Diani',
        location: 'Tropical Paradise',
        rating: 4.3,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/DianiWanderlust.jpg',
        category: 'beach',
      },
      {
        name: 'Watamu',
        location: 'Sunny Island',
        rating: 4.5,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card2.jpg',
        category: 'beach',
      },
      {
        name: 'Mombasa',
        location: 'Exotic Coast',
        rating: 4.7,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/card3.jpg',
        category: 'beach',
      },
      {
        name: 'Samburu',
        location: 'Jungle Adventure',
        rating: 4.6,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/SamburuWanderlust.jpg',
        category: 'safaris',
      },
      {
        name: 'Tsavo',
        location: 'Wild Savannah',
        rating: 4.2,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/TsavoWanderlust.jpg',
        category: 'safaris',
      },
      {
        name: 'Amboseli',
        location: 'Serengeti Plains',
        rating: 4.8,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/AmboseliWanderlust.jpg',
        category: 'safaris',
      },
      {
        name: 'Mt. Kenya',
        location: 'Kenya',
        rating: 4.4,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/Mt.+Kenya.jpeg',
        category: 'mountains',
      },
      {
        name: 'Mt. Kilimanjaro',
        location: 'Tanzania',
        rating: 4.9,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/Mt.+Kilimanjaro.jpeg',
        category: 'mountains',
      },
      {
        name: 'Mt. Longonot',
        location: 'Kenya',
        rating: 4.5,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/Mt.Kenya.jpg',
        category: 'mountains',
      },
      {
        name: 'Chania Falls',
        location: 'Kenya',
        rating: 4.1,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/Chania+Falls.jpeg',
        category: 'waterfall',
      },
      {
        name: 'Thompsons Falls',
        location: 'Kenya',
        rating: 4.6,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/Thomsons+Falls.jpeg',
        category: 'waterfall',
      },
      {
        name: 'Victoria Falls',
        location: 'Kenya',
        rating: 4.7,
        image: 'https://mywanderlustbucket.s3.eu-north-1.amazonaws.com/Victoria+falls.jpeg',
        category: 'waterfall',
      },
  
  ];